/*
 * This file is generated by jOOQ.
 */
package dev.mlnr.spidey.jooq.tables;


import dev.mlnr.spidey.jooq.Keys;
import dev.mlnr.spidey.jooq.Public;
import dev.mlnr.spidey.jooq.tables.records.InviteFilterIgnoredRolesRecord;
import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InviteFilterIgnoredRoles extends TableImpl<InviteFilterIgnoredRolesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.invite_filter_ignored_roles</code>
     */
    public static final InviteFilterIgnoredRoles INVITE_FILTER_IGNORED_ROLES = new InviteFilterIgnoredRoles();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<InviteFilterIgnoredRolesRecord> getRecordType() {
        return InviteFilterIgnoredRolesRecord.class;
    }

    /**
     * The column <code>public.invite_filter_ignored_roles.guild_id</code>.
     */
    public final TableField<InviteFilterIgnoredRolesRecord, Long> GUILD_ID = createField(DSL.name("guild_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.invite_filter_ignored_roles.role_id</code>.
     */
    public final TableField<InviteFilterIgnoredRolesRecord, Long> ROLE_ID = createField(DSL.name("role_id"), SQLDataType.BIGINT.nullable(false), this, "");

    private InviteFilterIgnoredRoles(Name alias, Table<InviteFilterIgnoredRolesRecord> aliased) {
        this(alias, aliased, null);
    }

    private InviteFilterIgnoredRoles(Name alias, Table<InviteFilterIgnoredRolesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.invite_filter_ignored_roles</code> table reference
     */
    public InviteFilterIgnoredRoles(String alias) {
        this(DSL.name(alias), INVITE_FILTER_IGNORED_ROLES);
    }

    /**
     * Create an aliased <code>public.invite_filter_ignored_roles</code> table reference
     */
    public InviteFilterIgnoredRoles(Name alias) {
        this(alias, INVITE_FILTER_IGNORED_ROLES);
    }

    /**
     * Create a <code>public.invite_filter_ignored_roles</code> table reference
     */
    public InviteFilterIgnoredRoles() {
        this(DSL.name("invite_filter_ignored_roles"), null);
    }

    public <O extends Record> InviteFilterIgnoredRoles(Table<O> child, ForeignKey<O, InviteFilterIgnoredRolesRecord> key) {
        super(child, key, INVITE_FILTER_IGNORED_ROLES);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public List<ForeignKey<InviteFilterIgnoredRolesRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<InviteFilterIgnoredRolesRecord, ?>>asList(Keys.INVITE_FILTER_IGNORED_ROLES__INVITE_FILTER_IGNORED_ROLES_GUILD_ID_FKEY);
    }

    private transient Guilds _guilds;

    public Guilds guilds() {
        if (_guilds == null)
            _guilds = new Guilds(this, Keys.INVITE_FILTER_IGNORED_ROLES__INVITE_FILTER_IGNORED_ROLES_GUILD_ID_FKEY);

        return _guilds;
    }

    @Override
    public InviteFilterIgnoredRoles as(String alias) {
        return new InviteFilterIgnoredRoles(DSL.name(alias), this);
    }

    @Override
    public InviteFilterIgnoredRoles as(Name alias) {
        return new InviteFilterIgnoredRoles(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public InviteFilterIgnoredRoles rename(String name) {
        return new InviteFilterIgnoredRoles(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public InviteFilterIgnoredRoles rename(Name name) {
        return new InviteFilterIgnoredRoles(name, null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<Long, Long> fieldsRow() {
        return (Row2) super.fieldsRow();
    }
}
