/*
 * This file is generated by jOOQ.
 */
package dev.mlnr.spidey.jooq.tables;


import dev.mlnr.spidey.jooq.Keys;
import dev.mlnr.spidey.jooq.Public;
import dev.mlnr.spidey.jooq.tables.records.SettingsBlacklistedChannelsRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SettingsBlacklistedChannels extends TableImpl<SettingsBlacklistedChannelsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.settings_blacklisted_channels</code>
     */
    public static final SettingsBlacklistedChannels SETTINGS_BLACKLISTED_CHANNELS = new SettingsBlacklistedChannels();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SettingsBlacklistedChannelsRecord> getRecordType() {
        return SettingsBlacklistedChannelsRecord.class;
    }

    /**
     * The column <code>public.settings_blacklisted_channels.guild_id</code>.
     */
    public final TableField<SettingsBlacklistedChannelsRecord, Long> GUILD_ID = createField(DSL.name("guild_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.settings_blacklisted_channels.channel_id</code>.
     */
    public final TableField<SettingsBlacklistedChannelsRecord, Long> CHANNEL_ID = createField(DSL.name("channel_id"), SQLDataType.BIGINT.nullable(false), this, "");

    private SettingsBlacklistedChannels(Name alias, Table<SettingsBlacklistedChannelsRecord> aliased) {
        this(alias, aliased, null);
    }

    private SettingsBlacklistedChannels(Name alias, Table<SettingsBlacklistedChannelsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.settings_blacklisted_channels</code> table reference
     */
    public SettingsBlacklistedChannels(String alias) {
        this(DSL.name(alias), SETTINGS_BLACKLISTED_CHANNELS);
    }

    /**
     * Create an aliased <code>public.settings_blacklisted_channels</code> table reference
     */
    public SettingsBlacklistedChannels(Name alias) {
        this(alias, SETTINGS_BLACKLISTED_CHANNELS);
    }

    /**
     * Create a <code>public.settings_blacklisted_channels</code> table reference
     */
    public SettingsBlacklistedChannels() {
        this(DSL.name("settings_blacklisted_channels"), null);
    }

    public <O extends Record> SettingsBlacklistedChannels(Table<O> child, ForeignKey<O, SettingsBlacklistedChannelsRecord> key) {
        super(child, key, SETTINGS_BLACKLISTED_CHANNELS);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public List<ForeignKey<SettingsBlacklistedChannelsRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<SettingsBlacklistedChannelsRecord, ?>>asList(Keys.SETTINGS_BLACKLISTED_CHANNELS__SETTINGS_BLACKLISTED_CHANNELS_GUILD_ID_FKEY);
    }

    private transient Guilds _guilds;

    public Guilds guilds() {
        if (_guilds == null)
            _guilds = new Guilds(this, Keys.SETTINGS_BLACKLISTED_CHANNELS__SETTINGS_BLACKLISTED_CHANNELS_GUILD_ID_FKEY);

        return _guilds;
    }

    @Override
    public SettingsBlacklistedChannels as(String alias) {
        return new SettingsBlacklistedChannels(DSL.name(alias), this);
    }

    @Override
    public SettingsBlacklistedChannels as(Name alias) {
        return new SettingsBlacklistedChannels(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public SettingsBlacklistedChannels rename(String name) {
        return new SettingsBlacklistedChannels(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public SettingsBlacklistedChannels rename(Name name) {
        return new SettingsBlacklistedChannels(name, null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<Long, Long> fieldsRow() {
        return (Row2) super.fieldsRow();
    }
}
