/*
 * This file is generated by jOOQ.
 */
package dev.mlnr.spidey.jooq.tables;


import dev.mlnr.spidey.jooq.Keys;
import dev.mlnr.spidey.jooq.Public;
import dev.mlnr.spidey.jooq.tables.records.SettingsWhitelistedChannelsRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SettingsWhitelistedChannels extends TableImpl<SettingsWhitelistedChannelsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.settings_whitelisted_channels</code>
     */
    public static final SettingsWhitelistedChannels SETTINGS_WHITELISTED_CHANNELS = new SettingsWhitelistedChannels();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SettingsWhitelistedChannelsRecord> getRecordType() {
        return SettingsWhitelistedChannelsRecord.class;
    }

    /**
     * The column <code>public.settings_whitelisted_channels.guild_id</code>.
     */
    public final TableField<SettingsWhitelistedChannelsRecord, Long> GUILD_ID = createField(DSL.name("guild_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.settings_whitelisted_channels.channel_id</code>.
     */
    public final TableField<SettingsWhitelistedChannelsRecord, Long> CHANNEL_ID = createField(DSL.name("channel_id"), SQLDataType.BIGINT.nullable(false), this, "");

    private SettingsWhitelistedChannels(Name alias, Table<SettingsWhitelistedChannelsRecord> aliased) {
        this(alias, aliased, null);
    }

    private SettingsWhitelistedChannels(Name alias, Table<SettingsWhitelistedChannelsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.settings_whitelisted_channels</code> table reference
     */
    public SettingsWhitelistedChannels(String alias) {
        this(DSL.name(alias), SETTINGS_WHITELISTED_CHANNELS);
    }

    /**
     * Create an aliased <code>public.settings_whitelisted_channels</code> table reference
     */
    public SettingsWhitelistedChannels(Name alias) {
        this(alias, SETTINGS_WHITELISTED_CHANNELS);
    }

    /**
     * Create a <code>public.settings_whitelisted_channels</code> table reference
     */
    public SettingsWhitelistedChannels() {
        this(DSL.name("settings_whitelisted_channels"), null);
    }

    public <O extends Record> SettingsWhitelistedChannels(Table<O> child, ForeignKey<O, SettingsWhitelistedChannelsRecord> key) {
        super(child, key, SETTINGS_WHITELISTED_CHANNELS);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public List<ForeignKey<SettingsWhitelistedChannelsRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<SettingsWhitelistedChannelsRecord, ?>>asList(Keys.SETTINGS_WHITELISTED_CHANNELS__SETTINGS_WHITELISTED_CHANNELS_GUILD_ID_FKEY);
    }

    private transient Guilds _guilds;

    public Guilds guilds() {
        if (_guilds == null)
            _guilds = new Guilds(this, Keys.SETTINGS_WHITELISTED_CHANNELS__SETTINGS_WHITELISTED_CHANNELS_GUILD_ID_FKEY);

        return _guilds;
    }

    @Override
    public SettingsWhitelistedChannels as(String alias) {
        return new SettingsWhitelistedChannels(DSL.name(alias), this);
    }

    @Override
    public SettingsWhitelistedChannels as(Name alias) {
        return new SettingsWhitelistedChannels(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public SettingsWhitelistedChannels rename(String name) {
        return new SettingsWhitelistedChannels(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public SettingsWhitelistedChannels rename(Name name) {
        return new SettingsWhitelistedChannels(name, null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<Long, Long> fieldsRow() {
        return (Row2) super.fieldsRow();
    }
}
