/*
 * This file is generated by jOOQ.
 */
package dev.mlnr.spidey.jooq;


import dev.mlnr.spidey.jooq.tables.Guilds;
import dev.mlnr.spidey.jooq.tables.SearchHistory;
import dev.mlnr.spidey.jooq.tables.SettingsMisc;
import dev.mlnr.spidey.jooq.tables.SettingsMusic;
import dev.mlnr.spidey.jooq.tables.records.GuildsRecord;
import dev.mlnr.spidey.jooq.tables.records.SearchHistoryRecord;
import dev.mlnr.spidey.jooq.tables.records.SettingsMiscRecord;
import dev.mlnr.spidey.jooq.tables.records.SettingsMusicRecord;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<GuildsRecord> GUILDS_PKEY = Internal.createUniqueKey(Guilds.GUILDS, DSL.name("guilds_pkey"), new TableField[] { Guilds.GUILDS.GUILD_ID }, true);
    public static final UniqueKey<SearchHistoryRecord> SEARCH_HISTORY_PK = Internal.createUniqueKey(SearchHistory.SEARCH_HISTORY, DSL.name("search_history_pk"), new TableField[] { SearchHistory.SEARCH_HISTORY.PK }, true);
    public static final UniqueKey<SettingsMiscRecord> SETTINGS_MISC_PKEY = Internal.createUniqueKey(SettingsMisc.SETTINGS_MISC, DSL.name("settings_misc_pkey"), new TableField[] { SettingsMisc.SETTINGS_MISC.GUILD_ID }, true);
    public static final UniqueKey<SettingsMusicRecord> SETTINGS_MUSIC_PKEY = Internal.createUniqueKey(SettingsMusic.SETTINGS_MUSIC, DSL.name("settings_music_pkey"), new TableField[] { SettingsMusic.SETTINGS_MUSIC.GUILD_ID }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<SettingsMiscRecord, GuildsRecord> SETTINGS_MISC__SETTINGS_MISC_GUILD_ID_FKEY = Internal.createForeignKey(SettingsMisc.SETTINGS_MISC, DSL.name("settings_misc_guild_id_fkey"), new TableField[] { SettingsMisc.SETTINGS_MISC.GUILD_ID }, Keys.GUILDS_PKEY, new TableField[] { Guilds.GUILDS.GUILD_ID }, true);
    public static final ForeignKey<SettingsMusicRecord, GuildsRecord> SETTINGS_MUSIC__SETTINGS_MUSIC_GUILD_ID_FKEY = Internal.createForeignKey(SettingsMusic.SETTINGS_MUSIC, DSL.name("settings_music_guild_id_fkey"), new TableField[] { SettingsMusic.SETTINGS_MUSIC.GUILD_ID }, Keys.GUILDS_PKEY, new TableField[] { Guilds.GUILDS.GUILD_ID }, true);
}
