/*
 * This file is generated by jOOQ.
 */
package dev.mlnr.spidey.jooq;


import dev.mlnr.spidey.jooq.tables.Guilds;
import dev.mlnr.spidey.jooq.tables.SettingsMisc;
import dev.mlnr.spidey.jooq.tables.SettingsMusic;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.guilds</code>.
     */
    public final Guilds GUILDS = Guilds.GUILDS;

    /**
     * The table <code>public.settings_misc</code>.
     */
    public final SettingsMisc SETTINGS_MISC = SettingsMisc.SETTINGS_MISC;

    /**
     * The table <code>public.settings_music</code>.
     */
    public final SettingsMusic SETTINGS_MUSIC = SettingsMusic.SETTINGS_MUSIC;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Guilds.GUILDS,
            SettingsMisc.SETTINGS_MISC,
            SettingsMusic.SETTINGS_MUSIC
        );
    }
}
