/*
 * This file is generated by jOOQ.
 */
package dev.mlnr.spidey.jooq;


import dev.mlnr.spidey.jooq.tables.Guilds;
import dev.mlnr.spidey.jooq.tables.MusicHistory;
import dev.mlnr.spidey.jooq.tables.SettingsMisc;
import dev.mlnr.spidey.jooq.tables.SettingsMusic;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.guilds</code>.
     */
    public static final Guilds GUILDS = Guilds.GUILDS;

    /**
     * The table <code>public.music_history</code>.
     */
    public static final MusicHistory MUSIC_HISTORY = MusicHistory.MUSIC_HISTORY;

    /**
     * The table <code>public.settings_misc</code>.
     */
    public static final SettingsMisc SETTINGS_MISC = SettingsMisc.SETTINGS_MISC;

    /**
     * The table <code>public.settings_music</code>.
     */
    public static final SettingsMusic SETTINGS_MUSIC = SettingsMusic.SETTINGS_MUSIC;
}
