/*
 * This file is generated by jOOQ.
 */
package dev.mlnr.spidey.jooq.tables.records;


import dev.mlnr.spidey.jooq.tables.Guilds;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GuildsRecord extends UpdatableRecordImpl<GuildsRecord> implements Record2<Long, Boolean> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.guilds.guild_id</code>.
     */
    public GuildsRecord setGuildId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.guilds.guild_id</code>.
     */
    public Long getGuildId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.guilds.vip</code>.
     */
    public GuildsRecord setVip(Boolean value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.guilds.vip</code>.
     */
    public Boolean getVip() {
        return (Boolean) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Long, Boolean> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Long, Boolean> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Guilds.GUILDS.GUILD_ID;
    }

    @Override
    public Field<Boolean> field2() {
        return Guilds.GUILDS.VIP;
    }

    @Override
    public Long component1() {
        return getGuildId();
    }

    @Override
    public Boolean component2() {
        return getVip();
    }

    @Override
    public Long value1() {
        return getGuildId();
    }

    @Override
    public Boolean value2() {
        return getVip();
    }

    @Override
    public GuildsRecord value1(Long value) {
        setGuildId(value);
        return this;
    }

    @Override
    public GuildsRecord value2(Boolean value) {
        setVip(value);
        return this;
    }

    @Override
    public GuildsRecord values(Long value1, Boolean value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GuildsRecord
     */
    public GuildsRecord() {
        super(Guilds.GUILDS);
    }

    /**
     * Create a detached, initialised GuildsRecord
     */
    public GuildsRecord(Long guildId, Boolean vip) {
        super(Guilds.GUILDS);

        setGuildId(guildId);
        setVip(vip);
    }
}
