/*
 * This file is generated by jOOQ.
 */
package dev.mlnr.spidey.jooq.tables.records;


import dev.mlnr.spidey.jooq.tables.InviteFilterIgnoredRoles;
import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InviteFilterIgnoredRolesRecord extends TableRecordImpl<InviteFilterIgnoredRolesRecord> implements Record2<Long, Long> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.invite_filter_ignored_roles.guild_id</code>.
     */
    public InviteFilterIgnoredRolesRecord setGuildId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.invite_filter_ignored_roles.guild_id</code>.
     */
    public Long getGuildId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.invite_filter_ignored_roles.role_id</code>.
     */
    public InviteFilterIgnoredRolesRecord setRoleId(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.invite_filter_ignored_roles.role_id</code>.
     */
    public Long getRoleId() {
        return (Long) get(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Long, Long> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Long, Long> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return InviteFilterIgnoredRoles.INVITE_FILTER_IGNORED_ROLES.GUILD_ID;
    }

    @Override
    public Field<Long> field2() {
        return InviteFilterIgnoredRoles.INVITE_FILTER_IGNORED_ROLES.ROLE_ID;
    }

    @Override
    public Long component1() {
        return getGuildId();
    }

    @Override
    public Long component2() {
        return getRoleId();
    }

    @Override
    public Long value1() {
        return getGuildId();
    }

    @Override
    public Long value2() {
        return getRoleId();
    }

    @Override
    public InviteFilterIgnoredRolesRecord value1(Long value) {
        setGuildId(value);
        return this;
    }

    @Override
    public InviteFilterIgnoredRolesRecord value2(Long value) {
        setRoleId(value);
        return this;
    }

    @Override
    public InviteFilterIgnoredRolesRecord values(Long value1, Long value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached InviteFilterIgnoredRolesRecord
     */
    public InviteFilterIgnoredRolesRecord() {
        super(InviteFilterIgnoredRoles.INVITE_FILTER_IGNORED_ROLES);
    }

    /**
     * Create a detached, initialised InviteFilterIgnoredRolesRecord
     */
    public InviteFilterIgnoredRolesRecord(Long guildId, Long roleId) {
        super(InviteFilterIgnoredRoles.INVITE_FILTER_IGNORED_ROLES);

        setGuildId(guildId);
        setRoleId(roleId);
    }
}
