/*
 * This file is generated by jOOQ.
 */
package dev.mlnr.spidey.jooq.tables.records;


import dev.mlnr.spidey.jooq.tables.SettingsBlacklistedChannels;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SettingsBlacklistedChannelsRecord extends TableRecordImpl<SettingsBlacklistedChannelsRecord> implements Record2<Long, Long> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.settings_blacklisted_channels.guild_id</code>.
     */
    public SettingsBlacklistedChannelsRecord setGuildId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.settings_blacklisted_channels.guild_id</code>.
     */
    public Long getGuildId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.settings_blacklisted_channels.channel_id</code>.
     */
    public SettingsBlacklistedChannelsRecord setChannelId(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.settings_blacklisted_channels.channel_id</code>.
     */
    public Long getChannelId() {
        return (Long) get(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Long, Long> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Long, Long> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return SettingsBlacklistedChannels.SETTINGS_BLACKLISTED_CHANNELS.GUILD_ID;
    }

    @Override
    public Field<Long> field2() {
        return SettingsBlacklistedChannels.SETTINGS_BLACKLISTED_CHANNELS.CHANNEL_ID;
    }

    @Override
    public Long component1() {
        return getGuildId();
    }

    @Override
    public Long component2() {
        return getChannelId();
    }

    @Override
    public Long value1() {
        return getGuildId();
    }

    @Override
    public Long value2() {
        return getChannelId();
    }

    @Override
    public SettingsBlacklistedChannelsRecord value1(Long value) {
        setGuildId(value);
        return this;
    }

    @Override
    public SettingsBlacklistedChannelsRecord value2(Long value) {
        setChannelId(value);
        return this;
    }

    @Override
    public SettingsBlacklistedChannelsRecord values(Long value1, Long value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SettingsBlacklistedChannelsRecord
     */
    public SettingsBlacklistedChannelsRecord() {
        super(SettingsBlacklistedChannels.SETTINGS_BLACKLISTED_CHANNELS);
    }

    /**
     * Create a detached, initialised SettingsBlacklistedChannelsRecord
     */
    public SettingsBlacklistedChannelsRecord(Long guildId, Long channelId) {
        super(SettingsBlacklistedChannels.SETTINGS_BLACKLISTED_CHANNELS);

        setGuildId(guildId);
        setChannelId(channelId);
    }
}
