/*
 * This file is generated by jOOQ.
 */
package dev.mlnr.spidey.jooq.tables.records;


import dev.mlnr.spidey.jooq.tables.SettingsWhitelistedChannels;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SettingsWhitelistedChannelsRecord extends UpdatableRecordImpl<SettingsWhitelistedChannelsRecord> implements Record2<Long, Long> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.settings_whitelisted_channels.guild_id</code>.
     */
    public SettingsWhitelistedChannelsRecord setGuildId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.settings_whitelisted_channels.guild_id</code>.
     */
    public Long getGuildId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.settings_whitelisted_channels.channel_id</code>.
     */
    public SettingsWhitelistedChannelsRecord setChannelId(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.settings_whitelisted_channels.channel_id</code>.
     */
    public Long getChannelId() {
        return (Long) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Long, Long> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Long, Long> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return SettingsWhitelistedChannels.SETTINGS_WHITELISTED_CHANNELS.GUILD_ID;
    }

    @Override
    public Field<Long> field2() {
        return SettingsWhitelistedChannels.SETTINGS_WHITELISTED_CHANNELS.CHANNEL_ID;
    }

    @Override
    public Long component1() {
        return getGuildId();
    }

    @Override
    public Long component2() {
        return getChannelId();
    }

    @Override
    public Long value1() {
        return getGuildId();
    }

    @Override
    public Long value2() {
        return getChannelId();
    }

    @Override
    public SettingsWhitelistedChannelsRecord value1(Long value) {
        setGuildId(value);
        return this;
    }

    @Override
    public SettingsWhitelistedChannelsRecord value2(Long value) {
        setChannelId(value);
        return this;
    }

    @Override
    public SettingsWhitelistedChannelsRecord values(Long value1, Long value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SettingsWhitelistedChannelsRecord
     */
    public SettingsWhitelistedChannelsRecord() {
        super(SettingsWhitelistedChannels.SETTINGS_WHITELISTED_CHANNELS);
    }

    /**
     * Create a detached, initialised SettingsWhitelistedChannelsRecord
     */
    public SettingsWhitelistedChannelsRecord(Long guildId, Long channelId) {
        super(SettingsWhitelistedChannels.SETTINGS_WHITELISTED_CHANNELS);

        setGuildId(guildId);
        setChannelId(channelId);
    }
}
