/*
 * This file is generated by jOOQ.
 */
package dev.mlnr.spidey.jooq.tables.records;


import dev.mlnr.spidey.jooq.tables.SettingsMisc;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SettingsMiscRecord extends UpdatableRecordImpl<SettingsMiscRecord> implements Record5<Long, Long, Long, Boolean, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.settings_misc.guild_id</code>.
     */
    public SettingsMiscRecord setGuildId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.settings_misc.guild_id</code>.
     */
    public Long getGuildId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.settings_misc.log_channel_id</code>.
     */
    public SettingsMiscRecord setLogChannelId(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.settings_misc.log_channel_id</code>.
     */
    public Long getLogChannelId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.settings_misc.join_role_id</code>.
     */
    public SettingsMiscRecord setJoinRoleId(Long value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.settings_misc.join_role_id</code>.
     */
    public Long getJoinRoleId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.settings_misc.sniping_enabled</code>.
     */
    public SettingsMiscRecord setSnipingEnabled(Boolean value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.settings_misc.sniping_enabled</code>.
     */
    public Boolean getSnipingEnabled() {
        return (Boolean) get(3);
    }

    /**
     * Setter for <code>public.settings_misc.language</code>.
     */
    public SettingsMiscRecord setLanguage(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.settings_misc.language</code>.
     */
    public String getLanguage() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Long, Long, Long, Boolean, String> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Long, Long, Long, Boolean, String> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return SettingsMisc.SETTINGS_MISC.GUILD_ID;
    }

    @Override
    public Field<Long> field2() {
        return SettingsMisc.SETTINGS_MISC.LOG_CHANNEL_ID;
    }

    @Override
    public Field<Long> field3() {
        return SettingsMisc.SETTINGS_MISC.JOIN_ROLE_ID;
    }

    @Override
    public Field<Boolean> field4() {
        return SettingsMisc.SETTINGS_MISC.SNIPING_ENABLED;
    }

    @Override
    public Field<String> field5() {
        return SettingsMisc.SETTINGS_MISC.LANGUAGE;
    }

    @Override
    public Long component1() {
        return getGuildId();
    }

    @Override
    public Long component2() {
        return getLogChannelId();
    }

    @Override
    public Long component3() {
        return getJoinRoleId();
    }

    @Override
    public Boolean component4() {
        return getSnipingEnabled();
    }

    @Override
    public String component5() {
        return getLanguage();
    }

    @Override
    public Long value1() {
        return getGuildId();
    }

    @Override
    public Long value2() {
        return getLogChannelId();
    }

    @Override
    public Long value3() {
        return getJoinRoleId();
    }

    @Override
    public Boolean value4() {
        return getSnipingEnabled();
    }

    @Override
    public String value5() {
        return getLanguage();
    }

    @Override
    public SettingsMiscRecord value1(Long value) {
        setGuildId(value);
        return this;
    }

    @Override
    public SettingsMiscRecord value2(Long value) {
        setLogChannelId(value);
        return this;
    }

    @Override
    public SettingsMiscRecord value3(Long value) {
        setJoinRoleId(value);
        return this;
    }

    @Override
    public SettingsMiscRecord value4(Boolean value) {
        setSnipingEnabled(value);
        return this;
    }

    @Override
    public SettingsMiscRecord value5(String value) {
        setLanguage(value);
        return this;
    }

    @Override
    public SettingsMiscRecord values(Long value1, Long value2, Long value3, Boolean value4, String value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SettingsMiscRecord
     */
    public SettingsMiscRecord() {
        super(SettingsMisc.SETTINGS_MISC);
    }

    /**
     * Create a detached, initialised SettingsMiscRecord
     */
    public SettingsMiscRecord(Long guildId, Long logChannelId, Long joinRoleId, Boolean snipingEnabled, String language) {
        super(SettingsMisc.SETTINGS_MISC);

        setGuildId(guildId);
        setLogChannelId(logChannelId);
        setJoinRoleId(joinRoleId);
        setSnipingEnabled(snipingEnabled);
        setLanguage(language);
    }
}
